#! /usr/bin/perl

my $patch = '0';

my @v = ();
my @voice1 = ("1 rest'\n");
my @voice2 = ("1 rest,\n");
my @voice3 = ();
my @voice4 = ();
my $ibar = 0;
while (<DATA>) {
	next if /^\s*$/;
	next if /^#/;
	last if /^quit/;
	chop;
	$v[$ibar] = $_;
	$ibar += 1;
}
$ibar = 1;
while (my $s4 = $v[$ibar]) {
	my ($h1, $h2) = split('   ',$s4);
	my $s2 = $v[$ibar-1];
	my ($h1bm1, $h2bm1) = split('   ', $s2);
	if (! $h2bm1) {
		warn "bar $ibar doesn't have 2 halves separated by 3 spaces\n";
	}
	my ($h1bm2, $h2bm2) = split('   ', $v[$ibar-2]);
	if ($ibar == 1) { $h2bm2 = "2 rest'"; }
	my $s1 = "$h2bm2 $h1bm1";
	$s1 =~ s/rest,/rest'/g;
	$s1 =~ s/([()])2/${1}1/g;
	$voice1[$ibar] = `echo "=1' cha1 $s1" | transpose +9 -A`;
	$voice2[$ibar] = `echo "=1, cha2 $s2" | transpose -2 -A`;
	my $s3 = "$h2bm1 $h1";
	$s3 =~ s/rest,/rest'/g;
	$s3 =~ s/([()])2/${1}1/g;
	$voice3[$ibar] = `echo "=2' cha3 $s3" | transpose +11 -A`;
	$voice4[$ibar] = "=2, cha4 $s4\n";
	$ibar += 1;
}

print <<EOT;
4 systems 10 /19-45-19/19-45-19/19-45-19/19-45-19 10/
pagenum
title Canon  at eleven semitones
leftfoot (c) 2010 Peter J Billam
# or: 73,71,70,70 or: 40,41,42,42 or 73,71,0,0
midi channel 1 patch $patch reverb 99 pan 95
midi channel 2 patch $patch reverb 99 pan 65
midi channel 3 patch $patch reverb 99 pan 35
midi channel 4 patch $patch reverb 99 pan 5
/
2 bars | 4/4 48 | 48 |
| 3.2
=1'  treble 4/4 cha1 leg99 $voice1[0]
=1,  treble 4/4 cha2 leg99 $voice2[0]
=2'  bass   4/4 cha3 leg99 2 rest'   8. c# 16 rest' 8. rest' 16 d#
=2,  bass   4/4 cha4 leg99 $v[0]
EOT

$ibar = 1; while (1) {
	if (2 == $ibar) { print "/\n2 bars | 48 | 48 |\n"; }
	print "|\n";
	if (4 == $ibar%5) { printf "il0.9 .20 %d\n",$ibar+1; }

	if (! $voice4[$ibar]) { last; }
	if ($ibar > 186) { last; }
	print $voice1[$ibar];
	print $voice2[$ibar];
	print $voice3[$ibar];
	print $voice4[$ibar];

	$ibar += 1;
}
exit 0;

__END__

# Overall plan: +0 +1 +1 +2 +1 +1 +2 +1 +3 +ending

# a=0 b=3 c=5 d=6 e=8 f=0 g=9 h=3
8. D 16 rest, 8. rest, 16 E   4. F 16 [F# G(2]
2 G)2   2 G#
4 A# 16 rest, 8. c   4. d 16 [c B(2]
8 [B)2 8. A# G#]   4 F Eb

# a=0 b=3 c=4 d=6 e=9 f=10 g=0 h=4
# 5
8. D 16 rest, 8. rest, 16 E   4. F 16 [F F#(2]
2 F#)2   4 G# 16 rest, 8. A
2 B   4. c 16 [c# d(2]
8 [d)2 8. B A]   4 F# E
# 8. Eb 16 rest, 8. rest, 16 Fn   4. F# 16 [F# G(2]
# 8. Eb 16 rest, 8. rest, 16 Fn   4 F# 8 [B 16 A G(2]
8. Eb 16 rest, 8. rest, 16 Fn   8 [F# 16 G# A#] 8 [B 16 An Gn(2]
# 10
4 G)2 16 rest, 8. G#   4 A 16 rest, 8. B
# 4 c 8. rest, 16 c   4. c# 16 [d eb(2]
# 4 c 8. rest, 16 c   4 c# 8 [g 16 f eb(2]
4 c 8. rest, 16 c#   8 [d 16 e f] 8 [g 16 fn eb(2]
8 [eb)2 8. cn 8 Bb 16 Ab]   4 G F

# a=0 b=1 c=5 d=6 e=8 f=0 g=1 h=7   a=2
# rise by 2 semitones
# 8. E 16 rest, 8. rest, 16 E   4. F 16 [G A(2]
8. E 16 rest, 8. rest, 16 E   8 [F 16 c d] 8 [c 16 B Bb]
4 A 16 rest, 8 [G 16 A]   4.. Bb 16 Bb
# 15
# 2 c   2 e
16 [c d c Bn] 8 [c d]   2 e
# 2 f   2 B
8. [f 8 eb d 16 c]   4. B 16 [A G]

# a=0 b=3 c=4 d=6 e=9 f=10 g=0 h=4
# 2 F#   2 A
4 F# G#   8. A 16 rest, 8. rest, 16 Bn
# 2 Bb   2 c
4 Bb 16 rest, 8. c(2   4. c)2 16 [c d]
# 2 d#   2 e
8. [d# 16 fn] 4 d#   4.. e 16 f#(2
# 20
# 2 f#   2 Bb
# 16 [f#)2 8 fn eb db 16 Bn]   4 Bb Ab
4 f#)2 16 rest, 8. c#   4 Bb Ab
# 2 G   2 Bb
4. G 8 An   4. Bb 16 [Bb Bn(2]
# 2 Bn   2 c#
4 Bn)2 16 rest, 8. cn   4 c# 16 rest, 8. d#
# 2 e   4 f f
4 e 16 [e cn dn e]   8. [f 16 g] 4 f
# 2 g   2 B
16 [g ab bb ab] [f# e d c]   4 B 16 [c# B A B]

# another rise by 2 semitones
# a=0 b=1 c=5 d=6 e=8 f=0 g=1 h=7   a=2
# 25
# 2 G#   2 A
16 [cn Bb Ab Bb] 4 Ab   16 [An Bn c A] [B c A# B]
# 2 c#   2 d
4 c# 16 [c# d# e c#]   16 [dn e] 4 d 16 [eb f]
# 2 e   2 g#
16 [en f# gn a] 8 [e 16 fn f#]   16 [g# bb g# bb] 8 [g# 16 f# g#]
#2 a   2 d#
8. [a 16 a(2] [a)2 gn fn e]   16 [d# c# 8 d#(2] 16 [d#)2 d# dn cn]

# last rise by one semitone
# a=0 b=3 c=4 d=6 e=9 f=10 g=0 h=4
#2 A#   2 c#
# 4. A# 16 [B c#(2]   4.. c#)2 16 d(2
8. [A# 16 cn] [dn A# B c#(2]   16 [c#)2 d# 8 c#(2] 16 [c#)2 d# e dn(2]
# 30
#2 d   2 e
16 [d)2 e f d(2] [d)2 e f e(2]   16 [e)2 f g e(2] [e)2 f f# g(2]
#2 g   2 ab
16 [g)2 ab bb g] [ab bb g an(2]   16 [an)2 bn c~# d~] [a b c~# b]
# 2 bb   2 d
32 [bb c~n bb c~ bb c~ bb c~] [bb c~ bb c~ bb c~ bb c~]   2 rest,

# rise by three semitones
# 2 B   2 c
2 rest,   4 rest, 8 [c d]
# 2 eb   2 en
4.. d# 16 e(2   4 e)2 16 rest, 8. f#(2
# 35
# 2 f#   2 g
#4.. f#)2 16 g(2   8 [g)2 8. fn d]
4 f#)2 8. [g 16 fn(2]    8 [f)2 8. d c#]
# 2 B   2 G
4 B A   4. G 8 D(2

# into the ending... 4. G 8 C
# 2 D   2 Eb
2 D)2   4 Eb 16 rest, 8. Ab
#2 Bb   2 G
4.. Bb 16 G(2   4. G)2 8 D(2
# 2 D   2 Eb
4.. D)2 16 Eb(2   8 [Eb)2 8. F 8 G 16 Ab]
# 40
#2 Bb   2 G
4.. Bb 16 G(2   4.. G)2 16 D(2
# a=0 b=5 c=0 d=5
2 D)2   2 G
2 D   2 G
2 D   2 G
2 D   2 blank

quit

# a=0 b=1 c=5 d=6 e=7 f=10 g=1 h=6   a=1
# good rise by one semitone
2 D   2 Eb
2 G   2 G#
2 A   2 c
2 eb   2 G#
2 D#   2 E
2 G#   2 A
2 Bb   2 c#
2 e   2 A
quit

# a=0 b=1 c=5 d=6 e=8 f=0 g=1 h=7   a=2
# possible rise by 2 semitones
2 D   2 Eb
2 G   2 G#
2 Bb   2 d
2 eb   2 A
2 E   2 F
2 A   2 Bb
2 c   2 e
2 f   2 B
quit

# a=0 b=1 c=4 d=7 e=8 f=3 g=10 h=7   a=2
# completely whole-toney; boring
2 D   2 Eb
2 F#   2 A
2 Bb   2 f
2 cn   2 A
2 E   2 F
2 G#   2 B
2 c   2 g
2 dn   2 B
quit

# a=0 b=1 c=6 d=7 e=8 f=1 g=2 h=7   a=2
2 D   2 Eb
2 G#   2 A
2 Bb   2 eb
2 en   2 A
2 E   2 F
2 A#   2 B
2 c   2 f
2 gb   2 B
quit

# a=0 b=1 c=8 d=5
# great ending!
2 D   2 Eb
2 Bb   2 G
2 D   2 Eb
2 Bb   2 G
# plug-compatible :-)
# a=0 b=5 c=0 d=5
# a possible finish on the D f# C e chord...
2 D   2 G
2 D   2 G
2 D   2 G
2 D   2 G
quit

# a=0 b=3 c=6 d=7 e=8 f=1 g=10 h=7
# not bad: shapely
2 D   2 F
2 G#   2 A
2 Bb   2 eb
2 c   2 A
2 D   2 F
2 G#   2 A
2 Bb   2 eb
2 c   2 A

# a=0 b=2 c=6 d=7 e=8 f=1 g=10 h=7
# basically, good :-)
2 D   2 E
# quibble: exposed 5th scnd-half this bar et seq
2 G#   2 A
2 Bb   2 eb
2 c   2 A
2 D   2 E
2 G#   2 A
2 Bb   2 eb
2 c   2 A
quit

# a=0 b=2 c=6 d=3 e=6 f=7 g=10 h=7
# the repeated G# is poor
2 D   2 E
2 G#   2 f
2 g#   2 a
2 c   2 A
2 D   2 E
2 G#   2 F
2 G#   2 A
2 c   2 A
quit

# a=0 b=2 c=8 d=3 e=4 f=7 g=10 h=7
# bit too leapy; chord on Bb sounds illogical
2 D   2 E
2 Bb   2 F
2 F#   2 A
2 c   2 A
2 D   2 E
2 Bb   2 F
2 F#   2 A
2 c   2 A
quit


# a=0 b=2 c=6 d=3 e=8 f=5 g=10 h=7
2 D   2 E
2 Ab   2 F
# 2nd half of this next bar sounds rough...
2 Bb   2 G
2 c   2 A
2 D   2 E
2 Ab   2 F
2 Bb   2 G
2 c   2 A

quit
# u u u u u u u D
8. D 16 rest, 8. rest, 16 D   8 E rest, 8 rest, 16 [D E]
8 F# rest, rest, 16 [E F#]   8 G# rest, 16 rest, [E F# G#]
8 A rest, rest, 16 [G# A]   8 A# rest, 16 rest, [G# An A#]
8 B rest, 16 rest, [An A# B]   4 c 16 [Bb Ab G F#]
8. D 16 rest, 8 rest, 16 [C# D]   8 E rest, 16 rest, [C# D E]
8 F# rest, 16 rest, [D E F#]   8 G# rest, 16 [D E F# G#]
8 A rest, 16 rest, [F# G# A]   8 A# rest, 16 [F# G# An A#]
8 B rest, 16 [G# An A# B]   8. c 16 B [Bb Ab Gn F#]
8. E 16 rest, 8 rest, 16 [E Fn]   8 F# rest, 16 rest, [E Fn F#]
# 10
8 G rest, 16 rest, [Fn F# G]   8 A rest, 16 [E F# G A]
8 Bb rest, 16 rest, [G Ab Bb]   4 c 16 [Bn Bb An G]
4 F# 8 [G leg50 G#]    8 leg99 [d B leg50 c leg99 eb]
8 [G leg50 G# leg99 d A]     8 leg50 [Bb leg99 16 eb Gn] leg40 [Ab leg99 en A# leg50 Bn]
2 blank   2 blank

quit

# u u u u u u D
2 D   2 E
2 F#   2 G#
2 A   2 Bb
2 Bn   2 D
2 E   2 F

quit
# u u u u u D
2 D   2 E
2 F#   2 G#
2 A   2 Bb
2 D   2 E
2 F   2 G
2 A   2 Bb
2 D   2 Eb
2 F   2 F#
2 G#   2 A#
2 C#   2 D#
2 E   2 F#

quit
8. D 16 rest, 8. rest, 16 D   8 E rest, 8 rest, 16 [D E]
8 F rest, 8. rest, 16 A   8 G# rest, 8 rest, 16 [E F#]
8 B rest, 16 rest, [c B A#]   8 G# rest, 16 [An B c c#]
8 d 16 rest, f [e d db cn]   8 A# 16 [F G] [An B c dn]
8. eb 16 rest, 4 rest,   2 rest,
4 Eb 8. rest, 16 F   2 F#


quit
8. D 16 rest, 8. rest, 16 D   8 E rest, 8 rest, 16 [D E]
8 F# rest, 16 rest, [D E F#]   8 G# rest, 16 [D E F# G#]
8 [Bb 16 rest, A] 8 [Abl 16 rest, G]   8 [Gb 16 rest, F] 8 [E 16 rest, Eb]
8. D 16 rest, 8. rest, 16 D   8 E rest, 8 rest, 16 [D E]
# 5
8 F rest, 16 rest, [D E F]   8 G rest, 16 [D E F G]
2 G#   8 [A# B leg50 fn] leg99 B
leg99 8 [c leg50 g] leg99 16 rest, leg99 [gb f leg50 B]   16 leg99 [eb d leg50 A leg99 db] [c A 8 Bb]
leg50 8 e leg99 [A# Bn leg50 c#]   8 leg99 [F# leg50 G] leg99 4 Eb
8. D 16 rest, 8. rest, 16 D   8 E rest, 8 rest, 16 [D E]
# 10
8 F# rest, 16 rest, [D E F#]   8 G# rest, 16 [D E F# G#]
#
#5 systems 10 /19-45-19/19-45-19/19-45-19/19-45-19/19-45-19 10/
#pagenum
#innerhead Canon  at eleven semitones, Peter Billam
#leftfoot (c) 2010 Peter J Billam
8. A 16 rest, 8. rest, 16 A   8 B rest, rest, 16 [A B]
8 c# rest, 16 rest, [A B c#]   2 d


