#! /usr/bin/perl
#########################################################################
#        This Perl script is Copyright (c) 1998, Peter J Billam         #
#     c/o P J B Computing, GPO Box 669, Hobart TAS 7001, Australia      #
#                                                                       #
# Permission is granted  to any individual or institution to use, copy, #
# modify or redistribute this software, so long as it is not resold for #
# profit,  and provided this notice is retained.   Neither Peter Billam #
# nor  P J B Computing  make any representations  about the suitability #
# of this software for any purpose. It is provided "as is", without any #
# express or implied warranty.                    http://www.pjb.com.au #
#########################################################################

$sd = '/home/pjb/www/mus/samples';

$message = 'Sample only.  Purchase the full score at www.pjb.com.au !';
open (I, "recordersuite.a4")     || die "can't open recordersuite.a4: $!\n";
open (O, "> $sd/recordersuite.a4") ||
	die "can't open $sd/recordersuite.a4: $!\n";

# output first two systems ...
while (<I>) { last if /% system 3 staves/; print O; }
while (<I>) { if (/centreshow$/) { print O; last; } }
while (<I>) { last if /^% system 3$/;   print O; }
print O "565 30 /Times-Italic 11 ($message) rightshow\n";

# skip to last system of Page 4
print O "0 40 translate\n";   # a bit upwards
while (<I>) { last if /^%%Page: 4 4/; }
while (<I>) { last if /^% system 4 staves/; }
# output last system ...
while (<I>) { last if /rightshow$/; print O; }
while (<I>) { last if /^% system 4$/; }
while (<I>) { print O; }

close I; close O;
